spring:
  application:
    name: feign-consumer-advance
server:
  port: 10006

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka

feign-client:
  ribbon:
    # 每台机器最大重试次数
    MaxAutoRetries: 2
    # 可以再重试几台机器
    MaxAutoRetriesNextServer: 2
    # 连接超时
    ConnectTimeout: 1000
    # 业务处理超时
    ReadTimeout: 2000
    # 在所有HTTP Method进行重试
    OkToRetryOnAllOperations: true
