spring:
  application:
    name: auth-service
  redis:
    database: 0
    host: localhost
    port: 6379
server:
  port: 10012

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/

logging:
  file: ${spring.application.name}.log

info:
  app:
    name: auth-service
    description: test

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always